public:
  app:
    mobileFontSize: 0px
    desktopFontSize: 0px
    audioChatNotification: false
    autoJoin: true
    listenOnlyMode: true
    forceListenOnly: false
    skipCheck: false
    skipCheckOnJoin: false
    clientTitle: BigBlueButton
    appName: My custom HTML5 client
    bbbServerVersion: 2.3-dev
    copyright: '©2021 TU Chemnitz'
    html5ClientBuild: EMPTY CHECK
    helpLink: https://empty_check.org/
    lockOnJoin: true
